# Generated by Django 3.0.5 on 2020-04-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_base', '0002_auto_20200427_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='header_def',
            field=models.TextField(default='The header', verbose_name='Заголовок'),
        ),
    ]
