# Generated by Django 3.0.5 on 2020-04-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_base', '0003_auto_20200427_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='definition',
        ),
        migrations.AddField(
            model_name='definition',
            name='category',
            field=models.TextField(default='The header', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='header_def',
            field=models.TextField(verbose_name='Заголовок'),
        ),
    ]
