# Generated by Django 3.0.5 on 2020-04-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('def_base', '0004_auto_20200427_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(verbose_name='Категория')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='def_base.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterField(
            model_name='definition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='def_base.Category', verbose_name='Категория'),
        ),
    ]
