# Generated by Django 3.0.5 on 2020-04-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_base', '0005_auto_20200427_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='category',
        ),
    ]
