# Generated by Django 3.0.5 on 2020-05-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_base', '0006_remove_definition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='set',
            field=models.TextField(default='1 1', verbose_name='Параметры'),
        ),
    ]
