# Generated by Django 3.0.5 on 2020-05-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('def_base', '0007_category_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='set',
            new_name='set_category',
        ),
    ]
