# Generated by Django 3.0.5 on 2020-05-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_base', '0008_auto_20200507_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='header_def',
            new_name='header',
        ),
        migrations.AddField(
            model_name='definition',
            name='question',
            field=models.TextField(default='The question', verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='set_category',
            field=models.TextField(default='1, 1', verbose_name='Параметры'),
        ),
    ]
