# Generated by Django 3.0.5 on 2020-05-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_base', '0010_auto_20200508_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='question',
            field=models.TextField(default='The question', verbose_name='Вопрос'),
        ),
    ]
