# Generated by Django 3.0.5 on 2020-05-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_base', '0011_auto_20200514_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='last_definition',
            field=models.TextField(default='None', verbose_name='Последнее определение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='start',
            field=models.TextField(default='start', verbose_name='Работа профиля'),
        ),
    ]
